### ISSUE TITLE
The loss of distillation dose not been calculated while used cwd distillation for the yoloX model

### ISSUE THREAD

**Issue by LZhangGJ** [open-mmlab/mmrazor#339] opened 2022-10-31 05:54 UTC
### Checklist

- The object-loss, the bbox-loss and the classification loss can be shown on the output log, but the Channel Wise Divergence loss seems not been calculated during training 

### Describe the question you meet

I use a yolox small model for distillation and train a yolox nano model. I defined a cwd loss in the "algorithm" to reduce the distance between bbox_head.multi_level_cls_convs.
However, according to the output log, it seems that the loss of this distance is not calculated. For example:
```
2022-10-31 11:37:26,568 - mmdet - INFO - Epoch [10][160/235]	lr: 1.000e-02, eta: 8:47:40, time: 0.541, data_time: 0.017, memory: 12199, student.loss_cls: 0.6404, student.loss_bbox: 4.2046, student.loss_obj: 7.8821, loss: 12.7272
```
I can't be sure if this is due to train_cfg. The current model looks as if it is training instead, but does not compute the distilled loss value.

### Post related information

1. The output of `pip list | grep "mmcv\|mmrazor\|^torch"`
mmcv-full                     1.5.0
mmrazor                       0.3.1
torch                         1.10.0
torchaudio                    0.10.0
torchvision                   0.11.0
2. Your config file if you modified it or created a new one.

```python
_base_ = ['/home/group/mmdetection/configs/_base_/schedules/schedule_1x.py', 
	  '/home/group/mmdetection/configs/_base_/default_runtime.py']

img_scale = (640, 640)  # height, width
classes = ['Target']
# model settings
teacher_ckpt = 'best.pth‘
teacher = dict(
    type='mmdet.YOLOX',
    init_cfg=dict(type='Pretrained', checkpoint=teacher_ckpt),
    input_size=img_scale,
    random_size_range=(15, 25),
    random_size_interval=10,
    backbone=dict(type='CSPDarknet', deepen_factor=0.33, widen_factor=0.5),
    neck=dict(
        type='YOLOXPAFPN',
        in_channels=[128, 256, 512],
        out_channels=128,
        num_csp_blocks=1),
    bbox_head=dict(
        type='YOLOXHead', num_classes=2, in_channels=128, feat_channels=128),
    train_cfg=dict(assigner=dict(type='SimOTAAssigner', center_radius=2.5)),
    test_cfg=dict(score_thr=0.01, nms=dict(type='nms', iou_threshold=0.65)))

student = dict(
    type='mmdet.YOLOX',
    #init_cfg=dict(type='Pretrained', checkpoint=teacher_ckpt),
    input_size=img_scale,
    random_size_range=(15, 25),
    random_size_interval=10,
    backbone=dict(type='CSPDarknet',deepen_factor=0.33, widen_factor=0.25, use_depthwise=True),
    neck=dict(
        type='YOLOXPAFPN',
        in_channels=[64, 128, 256],
        out_channels=128,
        num_csp_blocks=1),
    bbox_head=dict(
        type='YOLOXHead', num_classes=2, in_channels=128, feat_channels=128),
    train_cfg=dict(assigner=dict(type='SimOTAAssigner', center_radius=2.5)),
    test_cfg=dict(score_thr=0.01, nms=dict(type='nms', iou_threshold=0.65)))




algorithm = dict(
    type='GeneralDistill',
    architecture=dict(
        type='MMDetArchitecture',
        model=student,
    ),
    distiller=dict(
        type='SingleTeacherDistiller',
        teacher=teacher,
        teacher_trainable=False,
        components=[
            dict(
                student_module='bbox_head.multi_level_cls_convs',
                teacher_module='bbox_head.multi_level_cls_convs',
                losses=[
                    dict(
                        type='ChannelWiseDivergence',
                        name='loss_cwd_logits',
                        tau=1,
                        loss_weight=2,
                    )
                ])
        ]),
)


train_pipeline = [
    dict(type='Resize', img_scale=img_scale, keep_ratio=False),
    dict(type='YOLOXHSVRandomAug'),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(1, 1), keep_empty=False),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
dataset_type = 'CocoDataset'
train_dataset = dict(
    type='MultiImageMixDataset',
    dataset=dict(
        type=dataset_type,
        classes = classes,
        ann_file='dataset',
        img_prefix=None,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True)
        ],
        filter_empty_gt=False,
    ),
    pipeline=train_pipeline)

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_scale,
        flip=False,
        transforms=[
            dict(type='Resize', img_scale=img_scale, keep_ratio=False),
            dict(type='RandomFlip'),
            dict(
                type='Pad',
                pad_to_square=True,
                pad_val=dict(img=(114.0, 114.0, 114.0))),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]

data = dict(
    samples_per_gpu=24,
    workers_per_gpu=4,
    persistent_workers=True,
    train=train_dataset,
    val=dict(
        type=dataset_type,
        classes = classes,
        ann_file='dataset',
        img_prefix=None,
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        classes = classes,
        ann_file='dataset',
        img_prefix=None,
        pipeline=test_pipeline))

# optimizer
# default 8 gpu
optimizer = dict(
    type='SGD',
    lr=0.01,
    momentum=0.9,
    weight_decay=5e-4,
    nesterov=True,
    paramwise_cfg=dict(norm_decay_mult=0., bias_decay_mult=0.))
optimizer_config = dict(grad_clip=None)

max_epochs = 300
num_last_epochs = 15
resume_from = None
interval = 2

lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=2000,  # same as burn-in in darknet
    warmup_ratio=0.1,
    step=[218, 246])

runner = dict(type='EpochBasedRunner', max_epochs=max_epochs)

custom_hooks = [
    dict(
        type='YOLOXModeSwitchHook',
        num_last_epochs=num_last_epochs,
        priority=48),
    dict(
        type='SyncNormHook',
        num_last_epochs=num_last_epochs,
        interval=interval,
        priority=48),
    dict(
        type='ExpMomentumEMAHook',
        resume_from=resume_from,
        momentum=0.0001,
        priority=49)
]
checkpoint_config = dict(interval=interval*10)
evaluation = dict(
    save_best='auto',
    # The evaluation interval is 'interval' when running epoch is
    # less than ‘max_epochs - num_last_epochs’.
    # The evaluation interval is 1 when running epoch is greater than
    # or equal to ‘max_epochs - num_last_epochs’.
    interval=interval,
    dynamic_intervals=[(max_epochs - num_last_epochs, 1)],
    metric='bbox')
find_unused_parameters = True
log_config = dict(interval=20)
work_dir =  '/home/group/workspace/mmlab_mmrazor/work_dir/s3c_yolox_s_nano'
# NOTE: `auto_scale_lr` is for automatically scaling LR,
# USER SHOULD NOT CHANGE ITS VALUES.
# base_batch_size = (8 GPUs) x (8 samples per GPU)
auto_scale_lr = dict(base_batch_size=64)
```

3. Your train log file if you meet the problem during training.
```
 2022-10-31 11:37:26,568 - mmdet - INFO - Epoch [10][160/235]	lr: 1.000e-02, eta: 8:47:40, time: 0.541, data_time: 0.017, memory: 12199, student.loss_cls: 0.6404, student.loss_bbox: 4.2046, student.loss_obj: 7.8821, loss: 12.7272
2022-10-31 11:37:34,286 - mmdet - INFO - Epoch [10][180/235]	lr: 1.000e-02, eta: 8:46:44, time: 0.386, data_time: 0.020, memory: 12199, student.loss_cls: 0.4388, student.loss_bbox: 4.8402, student.loss_obj: 7.3535, loss: 12.6326
2022-10-31 11:37:43,651 - mmdet - INFO - Epoch [10][200/235]	lr: 1.000e-02, eta: 8:46:38, time: 0.468, data_time: 0.018, memory: 12199, student.loss_cls: 0.6874, student.loss_bbox: 4.2878, student.loss_obj: 6.4107, loss: 11.3858
2022-10-31 11:37:53,220 - mmdet - INFO - Epoch [10][220/235]	lr: 1.000e-02, eta: 8:46:37, time: 0.479, data_time: 0.017, memory: 12199, student.loss_cls: 0.6701, student.loss_bbox: 4.1327, student.loss_obj: 6.0989, loss: 10.9017
```
4. Other code you modified in the `mmrazor` folder.
nothing

**Comment by wilxy** [comment] 2022-10-31 12:39
Thank you for your issue.

This phenomenon is caused by a small error in your config:
``` 
components=[
    dict(
        student_module='bbox_head.multi_level_cls_convs',
        teacher_module='bbox_head.multi_level_cls_convs',
``` 

As shown in [YOLOX](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/yolox_head.py#L132), the type of `multi_level_cls_convs`  is `nn.ModuleList()`. Please change it to:
``` 
components=[ 
    dict( 
          student_module='bbox_head.multi_level_cls_convs.XXX', 
          teacher_module='bbox_head.multi_level_cls_convs.XXX',
```
where **XXX** is the specific `conv` in `multi_level_cls_convs` that you want to distill.

**Comment by LZhangGJ** [comment] 2022-11-01 01:39
Thanks for your replay. It's useful to me.
But there‘s another question.
The multi_level_cls_convslooks like this:
```
ModuleList(
  (0): Conv2d(128, 2, kernel_size=(1, 1), stride=(1, 1))
  (1): Conv2d(128, 2, kernel_size=(1, 1), stride=(1, 1))
  (2): Conv2d(128, 2, kernel_size=(1, 1), stride=(1, 1))
)
```
How can I select an unnamed layer in this ModuleList?  
I tried ```student_module='bbox_head.multi_level_cls_convs[2]',```
but
```
KeyError: "GeneralDistill: 'bbox_head.multi_level_cls_convs[2]'"
```
was found. It is unable to registry by the index of the layer.

**Comment by wilxy** [comment] 2022-11-01 02:36
Please change it to:
```
components=[ 
    dict( 
          student_module='bbox_head.multi_level_cls_convs.2.conv', 
          teacher_module='bbox_head.multi_level_cls_convs.2.conv',
```

**Comment by LZhangGJ** [comment] 2022-11-01 03:16
It works for me. Thank you.

**Comment by LZhangGJ** [comment] 2022-11-01 03:33
Thank you! It works for me.

**Comment by wilxy** [comment] 2022-11-04 06:16
I will close this issue. Please reopen it if there are any problems in the future.

**Closed by wilxy** 2022-11-04 06:16 UTC
Labels: usage
